export const ADD_COMPANY_REQUEST = 'ADD_COMPANY_REQUEST';
export const ADD_COMPANY_SUCCEED = 'ADD_COMPANY_SUCCEED';
export const ADD_COMPANY_FAILED = 'ADD_COMPANY_FAILED';

export const UPDATE_COMPANY_REQUEST = 'UPDATE_COMPANY_REQUEST';
export const UPDATE_COMPANY_SUCCEED = 'UPDATE_COMPANY_SUCCEED';
export const UPDATE_COMPANY_FAILED = 'UPDATE_COMPANY_FAILED';

export const COMPANY_DETAILS_GETTING_REQUEST= 'COMPANY_DETAILS_GETTING_REQUEST';
export const COMPANY_DETAILS_GETTING_SUCCEED= 'COMPANY_DETAILS_GETTING_SUCCEED';
export const COMPANY_DETAILS_GETTING_FAILED= 'COMPANY_DETAILS_GETTING_FAILED';

export const COMPANY_INACTIVE_REQUEST='COMPANY_INACTIVE_REQUEST';
export const COMPANY_INACTIVE_SUCCEED='COMPANY_INACTIVE_SUCCEED';
export const COMPANY_INACTIVE_FAILED='COMPANY_INACTIVE_FAILED';

export const COMPANY_ACTIVE_REQUEST='COMPANY_ACTIVE_REQUEST';
export const COMPANY_ACTIVE_SUCCEED='COMPANY_ACTIVE_SUCCEED';
export const COMPANY_ACTIVE_FAILED='COMPANY_ACTIVE_FAILED';

export const COMPANY_SEARCH_REQUEST='COMPANY_SEARCH_REQUEST';
export const COMPANY_SEARCH_SUCCEED='COMPANY_SEARCH_SUCCEED';
export const COMPANY_SEARCH_FAILED='COMPANY_SEARCH_FAILED';

export const COMPANY_ACTIVE_USERS_GETTING_REQUEST='COMPANY_ACTIVE_USERS_GETTING_REQUEST';
export const COMPANY_ACTIVE_USERS_GETTING_SUCCEED='COMPANY_ACTIVE_USERS_GETTING_SUCCEED';
export const COMPANY_ACTIVE_USERS_GETTING_FAILED='COMPANY_ACTIVE_USERS_GETTING_FAILED';


