export const ADD_DOCUMENT_REQUEST = 'ADD_DOCUMENT_REQUEST';
export const ADD_DOCUMENT_SUCCEED = 'ADD_DOCUMENT_SUCCEED';
export const ADD_DOCUMENT_FAILED = 'ADD_DOCUMENT_FAILED';

export const UPDATE_DOCUMENT_REQUEST = 'UPDATE_DOCUMENT_REQUEST';
export const UPDATE_DOCUMENT_SUCCEED = 'UPDATE_DOCUMENT_SUCCEED';
export const UPDATE_DOCUMENT_FAILED = 'UPDATE_DOCUMENT_FAILED';

export const DOCUMENT_DETAILS_GETTING_REQUEST= 'DOCUMENT_DETAILS_REQUEST';
export const DOCUMENT_DETAILS_GETTING_SUCCEED= 'DOCUMENT_DETAILS_SUCCEED';
export const DOCUMENT_DETAILS_GETTING_FAILED= 'DOCUMENT_DETAILS_FAILED';

export const DOCUMENT_DELETE_REQUEST='DOCUMENT_DELETE_REQUEST';
export const DOCUMENT_DELETE_SUCCEED='DOCUMENT_DELETE_SUCCEED';
export const DOCUMENT_DELETE_FAILED='DOCUMENT_DELETE_FAILED';

export const DOCUMENT_SEARCH_REQUEST='DOCUMENT_SEARCH_REQUEST';
export const DOCUMENT_SEARCH_SUCCEED='DOCUMENT_SEARCH_SUCCEED';
export const DOCUMENT_SEARCH_FAILED='DOCUMENT_SEARCH_FAILED';

export const DOCUMENT_SHARING_LINK_GETTING_REQUEST= 'DOCUMENT_SHARING_LINK_REQUEST';
export const DOCUMENT_SHARING_LINK_GETTING_SUCCEED= 'DOCUMENT_SHARING_LINK_SUCCEED';
export const DOCUMENT_SHARING_LINK_GETTING_FAILED= 'DOCUMENT_SHARING_LINK_FAILED';

export const DOCUMENT_UNSHARE_REQUEST= 'DOCUMENT_UNSHARE_REQUEST';
export const DOCUMENT_UNSHARE_SUCCEED= 'DOCUMENT_UNSHARE_SUCCEED';
export const DOCUMENT_UNSHARE_FAILED= 'DOCUMENT_UNSHARE_FAILED';