export const FILE_ADD_REQUEST = "FILE_ADD_REQUEST";
export const FILE_ADD_FAILED = "FILE_ADD_FAILED";
export const FILE_ADD_SUCCEED = "FILE_ADD_SUCCEED";

export const FILE_UPDATE_REQUEST = "FILE_UPDATE_REQUEST";
export const FILE_UPDATE_FAILED = "FILE_UPDATE_FAILED";
export const FILE_UPDATE_SUCCEED = "FILE_UPDATE_SUCCEED";

export const FILE_DETAILS_GETTING_REQUEST= 'FILE_DETAILS_GETTING_REQUEST';
export const FILE_DETAILS_GETTING_SUCCEED= 'FILE_DETAILS_GETTING_SUCCEED';
export const FILE_DETAILS_GETTING_FAILED= 'FILE_DETAILS_GETTING_FAILED';

export const FILE_INACTIVE_REQUEST='FILE_INACTIVE_REQUEST';
export const FILE_INACTIVE_SUCCEED='FILE_INACTIVE_SUCCEED';
export const FILE_INACTIVE_FAILED='FILE_INACTIVE_FAILED';