export const GROUP_DETAILS_GETTING_REQUEST= 'GROUP_DETAILS_REQUEST';
export const GROUP_DETAILS_GETTING_SUCCEED= 'GROUP_DETAILS_SUCCEED';
export const GROUP_DETAILS_GETTING_FAILED= 'GROUP_DETAILS_FAILED';