export const PACKAGE_DETAILS_GETTING_REQUEST= 'PACKAGE_DETAILS_GETTING_REQUEST';
export const PACKAGE_DETAILS_GETTING_SUCCEED= 'PACKAGE_DETAILS_GETTING_SUCCEED';
export const PACKAGE_DETAILS_GETTING_FAILED= 'PACKAGE_DETAILS_GETTING_FAILED';


