export const ROLE_DETAILS_GETTING_REQUEST= 'ROLE_DETAILS_REQUEST';
export const ROLE_DETAILS_GETTING_SUCCEED= 'ROLE_DETAILS_SUCCEED';
export const ROLE_DETAILS_GETTING_FAILED= 'ROLE_DETAILS_FAILED';


