export const TAG_ADD_REQUEST = "TAG_ADD_REQUEST";
export const TAG_ADD_FAILED = "TAG_ADD_FAILED";
export const TAG_ADD_SUCCEED = "TAG_ADD_SUCCEED";

export const TAG_UPDATE_REQUEST = "TAG_UPDATE_REQUEST";
export const TAG_UPDATE_FAILED = "TAG_UPDATE_FAILED";
export const TAG_UPDATE_SUCCEED = "TAG_UPDATE_SUCCEED";

export const TAG_DETAILS_GETTING_REQUEST= 'TAG_DETAILS_GETTING_REQUEST';
export const TAG_DETAILS_GETTING_SUCCEED= 'TAG_DETAILS_GETTING_SUCCEED';
export const TAG_DETAILS_GETTING_FAILED= 'TAG_DETAILS_GETTING_FAILED';

export const CHILDREN_TAG_DETAILS_GETTING_REQUEST= 'CHILDREN_TAG_DETAILS_GETTING_REQUEST';
export const CHILDREN_TAG_DETAILS_GETTING_SUCCEED= 'CHILDREN_TAG_DETAILS_GETTING_SUCCEED';
export const CHILDREN_TAG_DETAILS_GETTING_FAILED= 'CHILDREN_TAG_DETAILS_GETTING_FAILED';

export const TAG_INACTIVE_REQUEST='TAG_INACTIVE_REQUEST';
export const TAG_INACTIVE_SUCCEED='TAG_INACTIVE_SUCCEED';
export const TAG_INACTIVE_FAILED='TAG_INACTIVE_FAILED';

export const TAG_SEARCH_REQUEST='TAG_SEARCH_REQUEST';
export const TAG_SEARCH_SUCCEED='TAG_SEARCH_SUCCEED';
export const TAG_SEARCH_FAILED='TAG_SEARCH_FAILED';