export const ADD_USER_GROUP_REQUEST = 'ADD_USER_GROUP_REQUEST';
export const ADD_USER_GROUP_SUCCEED = 'ADD_USER_GROUP_SUCCEED';
export const ADD_USER_GROUP_FAILED = 'ADD_USER_GROUP_FAILED';

export const UPDATE_USER_GROUP_REQUEST = 'UPDATE_USER_GROUP_REQUEST';
export const UPDATE_USER_GROUP_SUCCEED = 'UPDATE_USER_GROUP_SUCCEED';
export const UPDATE_USER_GROUP_FAILED = 'UPDATE_USER_GROUP_FAILED';

export const USER_GROUP_DETAILS_GETTING_REQUEST= 'USER_GROUP_DETAILS_REQUEST';
export const USER_GROUP_DETAILS_GETTING_SUCCEED= 'USER_GROUP_DETAILS_SUCCEED';
export const USER_GROUP_DETAILS_GETTING_FAILED= 'USER_GROUP_DETAILS_FAILED';

export const USER_GROUP_DELETE_REQUEST='USER_GROUP_DELETE_REQUEST';
export const USER_GROUP_DELETE_SUCCEED='USER_GROUP_DELETE_SUCCEED';
export const USER_GROUP_DELETE_FAILED='USER_GROUP_DELETE_FAILED';

export const USER_GROUP_SEARCH_REQUEST='USER_GROUP_SEARCH_REQUEST';
export const USER_GROUP_SEARCH_SUCCEED='USER_GROUP_SEARCH_SUCCEED';
export const USER_GROUP_SEARCH_FAILED='USER_GROUP_SEARCH_FAILED';
