export const ADD_USERROLE_REQUEST = 'ADD_USERROLE_REQUEST';
export const ADD_USERROLE_SUCCEED = 'ADD_USERROLE_SUCCEED';
export const ADD_USERROLE_FAILED = 'ADD_USERROLE_FAILED';

export const UPDATE_USERROLE_REQUEST = 'UPDATE_USERROLE_REQUEST';
export const UPDATE_USERROLE_SUCCEED = 'UPDATE_USERROLE_SUCCEED';
export const UPDATE_USERROLE_FAILED = 'UPDATE_USERROLE_FAILED';

export const USERROLE_DETAILS_GETTING_REQUEST= 'USERROLE_DETAILS_GETTING_REQUEST';
export const USERROLE_DETAILS_GETTING_SUCCEED= 'USERROLE_DETAILS_GETTING_SUCCEED';
export const USERROLE_DETAILS_GETTING_FAILED= 'USERROLE_DETAILS_GETTING_FAILED';

export const USERROLE_INACTIVE_REQUEST='USERROLE_INACTIVE_REQUEST';
export const USERROLE_INACTIVE_SUCCEED='USERROLE_INACTIVE_SUCCEED';
export const USERROLE_INACTIVE_FAILED='USERROLE_INACTIVE_FAILED';

export const USERROLE_ACTIVE_REQUEST='USERROLE_ACTIVE_REQUEST';
export const USERROLE_ACTIVE_SUCCEED='USERROLE_ACTIVE_SUCCEED';
export const USERROLE_ACTIVE_FAILED='USERROLE_ACTIVE_FAILED';

export const USERROLE_SEARCH_REQUEST='USERROLE_SEARCH_REQUEST';
export const USERROLE_SEARCH_SUCCEED='USERROLE_SEARCH_SUCCEED';
export const USERROLE_SEARCH_FAILED='USERROLE_SEARCH_FAILED';

export const USERROLE_ACTIVE_USERS_GETTING_REQUEST='USERROLE_ACTIVE_USERS_GETTING_REQUEST';
export const USERROLE_ACTIVE_USERS_GETTING_SUCCEED='USERROLE_ACTIVE_USERS_GETTING_SUCCEED';
export const USERROLE_ACTIVE_USERS_GETTING_FAILED='USERROLE_ACTIVE_USERS_GETTING_FAILED';


