export const USER_ADD_REQUEST = "USER_ADD_REQUEST";
export const USER_ADD_FAILED = "USER_ADD_FAILED";
export const USER_ADD_SUCCEED = "USER_ADD_SUCCEED";

export const USER_UPDATE_REQUEST = "USER_UPDATE_REQUEST";
export const USER_UPDATE_FAILED = "USER_UPDATE_FAILED";
export const USER_UPDATE_SUCCEED = "USER_UPDATE_SUCCEED";

export const USER_DETAILS_GETTING_REQUEST= 'USER_DETAILS_REQUEST';
export const USER_DETAILS_GETTING_SUCCEED= 'USER_DETAILS_SUCCEED';
export const USER_DETAILS_GETTING_FAILED= 'USER_DETAILS_FAILED';

export const USER_INACTIVE_REQUEST='USER_INACTIVE_REQUEST';
export const USER_INACTIVE_SUCCEED='USER_INACTIVE_SUCCEED';
export const USER_INACTIVE_FAILED='USER_INACTIVE_FAILED';

export const USER_SEARCH_REQUEST='USER_SEARCH_REQUEST';
export const USER_SEARCH_SUCCEED='USER_SEARCH_SUCCEED';
export const USER_SEARCH_FAILED='USER_SEARCH_FAILED';



