export const ADD_WORKFLOW_REQUEST = 'ADD_WORKFLOW_REQUEST';
export const ADD_WORKFLOW_SUCCEED = 'ADD_WORKFLOW_SUCCEED';
export const ADD_WORKFLOW_FAILED = 'ADD_WORKFLOW_FAILED';

export const UPDATE_WORKFLOW_REQUEST = 'UPDATE_WORKFLOW_REQUEST';
export const UPDATE_WORKFLOW_SUCCEED = 'UPDATE_WORKFLOW_SUCCEED';
export const UPDATE_WORKFLOW_FAILED = 'UPDATE_WORKFLOW_FAILED';

export const WORKFLOW_DETAILS_GETTING_REQUEST= 'WORKFLOW_DETAILS_GETTING_REQUEST';
export const WORKFLOW_DETAILS_GETTING_SUCCEED= 'WORKFLOW_DETAILS_GETTING_SUCCEED';
export const WORKFLOW_DETAILS_GETTING_FAILED= 'WORKFLOW_DETAILS_GETTING_FAILED';

export const WORKFLOW_DELETE_REQUEST='WORKFLOW_DELETE_REQUEST';
export const WORKFLOW_DELETE_SUCCEED='WORKFLOW_DELETE_SUCCEED';
export const WORKFLOW_DELETE_FAILED='WORKFLOW_DELETE_FAILED';

export const WORKFLOW_SEARCH_REQUEST='WORKFLOW_SEARCH_REQUEST';
export const WORKFLOW_SEARCH_SUCCEED='WORKFLOW_SEARCH_SUCCEED';
export const WORKFLOW_SEARCH_FAILED='WORKFLOW_SEARCH_FAILED';

export const WORKFLOW_DETAILS_GETTING_BY_USERID_REQUEST= 'WORKFLOW_DETAILS_GETTING_BY_USERID_REQUEST';
export const WORKFLOW_DETAILS_GETTING_BY_USERID_SUCCEED= 'WORKFLOW_DETAILS_GETTING_BY_USERID_SUCCEED';
export const WORKFLOW_DETAILS_GETTING_BY_USERID_FAILED= 'WORKFLOW_DETAILS_GETTING_BY_USERID_FAILED';


